development:
  adapter: postgresql
  encoding: utf8
  database: save_point_development
  pool: 5


test: &TEST
  adapter: postgresql
  encoding: utf8
  database: save_point_test
  pool: 5


production:
  adapter: postgresql
  encoding: utf8
  database: save_point_production
  pool: 5
